export const ImgHost='http://192.168.88.13:8098/attachs';
export const HOST='http://192.168.88.13:8098/xhqpark';  //端口号
export const LoginAPI='/mobile/login/login';  //登录
export const PropertyAPI = '/mobile/news/estatenews'; //物业接口
export const PropertyDetailsAPI = '/mobile/news/display'; //物业详细
export const EnterInfoAPI = '/mobile/login/myinfo'; //企业信息
export const UpdatePasswordAPI = '/mobile/login/changePwd'; //修改密码
export const ComplainAPI = '/mobile/taskService/applyForCommon'; //发布公告
export const PaylsitAPI = '/mobile/estbillpayapi/list'; //缴费列表
export const PayAPI = '/mobile/estbillpayapi/save'; //缴费
export const PayDetailAPI = '/mobile/estbillpayapi/display'; //缴费详情
export const PublishImgAPI = '/mobile/taskService/saveEstTaskWithAttach'; //发布任务
export const TaskHomeAPI = '/mobile/taskService/getMyApplyTaskList'; //我的任务发布列表
export const LikeAPI = '/mobile/taskService/like'; //我的任务发布点赞
export const CheckAPI = '/mobile/taskService/displayEstTask'; //我的任务详细
export const CommentAPI = '/mobile/taskService/saveEstTaskComment'; //我的任务发布评论
export const TaskProcessListAPI = '/mobile/taskService/getTaskProcessList'; //物业人员任务处理列表
export const TaskProcessCommentAPI = '/mobile/taskService/saveTaskProcess'; //物业人员处理评论
export const TaskProcessCheckAPI = '/mobile/taskService/displayTaskProcess'; //物业人员处理评论
export const NewsListAPI = '/mobile/news/parknews'; //园区新闻
export const NewsDetailAPI = '/mobile/news/parknewsinfo'; //园区新闻详细
export const NoticeListAPI = '/mobile/news/parknotices'; //园区新闻
export const NoticeDetailAPI = '/mobile/news/parknoticeinfo/'; //园区新闻详细
export const EntListAPI = '/mobile/ent/entlist'; //园区企业列表
export const EntDetailAPI = '/mobile/ent/entinfo'; //园区企业详细
